new-team-project-name/front-end

assets/scripts/event/api.js
assets/scripts/event/events.js
assets/scripts/event/ui.js

--Setup initial js files to send new event to API.

Add event creator

---

assets/scripts/templates/show-events.handlebars

--added baseline handlers file to display event feed from event
index.

Setup initial handlebars file

---

assets/styles/index.scss
index.html

Style buttons, dropdowns/ups, and fonts

---

assets/scripts/hangout/api.js
assets/scripts/hangout/events.js
assets/scripts/templates/show-hangouts.handlebars

Edited Hangout posting event & api to correctly connect to backend
Fixed issue with handlebar having two date fields

Connect Post API & event to backend

---

assets/scripts/hangout/events.js
assets/scripts/templates/show-hangouts.handlebars

--Added attend button to event cards served through handlebars.
The data id for each button is 'attend-<id>'

Add attend button

---

assets/scripts/app.js
assets/scripts/auth/ui.js
assets/styles/index.scss
index.html

- Erin & @ehaffey
- Added messages to update clients about unsuccessful sign up/sign in attempts

Add messaging to unsuccessful sign up and login

---

assets/scripts/hangout/ui.js
assets/scripts/templates/show-hangouts.handlebars
assets/styles/index.scss

- Erin & @SorenHopkins & @ehaffey
- Events now have ownership meaning only owners have buttons to edit or delete

Add editable true or false value to hangout event

---

assets/scripts/templates/show-hangouts.handlebars
assets/styles/index.scss
index.html

- Erin adjusted the edit, update, add event, save changes, and RSVP buttons

Format buttons in handlebars and html using css

---

assets/styles/index.scss
index.html

- Erin changed the nav links to buttons to make content easier to read.

Format the nav buttons

---

assets/scripts/auth/ui.js
assets/styles/index.scss
index.html

- Erin added sign out failure message.
- Checked sign out functionality.
- Checked for message bugs.

Check sign out functionality and message

---

assets/scripts/auth/ui.js

- Erin sign out success message and auto disappear.

Add sign out success messaging

---

index.html

- Erin add change password functionality.
- Check change password failure message.
- Styled nav buttons and modal buttons.

Add change password functionality

---

README.md
assets/scripts/app.js
assets/scripts/auth/ui.js

Code added to app.js to clear sign in and change password error messages in their respective modals when the modals are closed.

Clear messages in modals

---

assets/scripts/templates/show-hangouts.handlebars
assets/styles/index.scss

Utilized bootstrap Card formatting option with Hangouts

Format 'Hangouts' to Card

---

assets/scripts/auth/ui.js
assets/scripts/hangout/api.js
assets/scripts/hangout/events.js
assets/scripts/hangout/ui.js
assets/styles/index.scss
index.html

- Erin added sign out success notification and style.
- Added jQuery and JS code to notify if a user has sent an RSVP.
- Styled RSVP notifications.

Add RSVP notification messages

---

assets/scripts/templates/show-hangouts.handlebars
assets/styles/index.scss
index.html

Formatted columns to display in single rows, at different sizes
according to the size of the user's screen.

Set styling for Card columns

---

assets/scripts/auth/ui.js

--Added 2 second text to alert div when authenticated users update
their password.

Add user alert when password updates

---

assets/scripts/app.js
assets/scripts/auth/ui.js
assets/scripts/templates/show-hangouts.handlebars
assets/styles/index.scss
index.html

- Erin worked on modals, event appearance, buttons.

Adjust button alignment and general appearance

---

assets/scripts/hangout/ui.js

- Erin added code to reset forms on submit

Clear Add Event form fields on submit

---

assets/scripts/templates/show-hangouts.handlebars
assets/styles/index.scss
index.html

- Erin fixed the edit event button to follow the style of the page.
- Adjusted notification box size again.

Adjust edit event button to match styling
